# Fishery Landings
{{< include _setup.qmd >}}

**Description** Fishery landings are indicators of ecosystem services provided and also reflect removals from the CCE. Commercial landings data are best summarized by the Pacific Fisheries Information Network (PacFIN; pacfin.psmfc.org), and recreational landings are best summarized by the Recreational Fisheries Information Network (RecFIN; www.recfin.org). Landings provide the best long-term indicator of fisheries removals. Status and trends are estimated relative to a frame of reference of 1991-2020. In most cases, landings data for the most recent reporting years are only complete through the latter months (e.g., October-December); these data are updated in the next annual cycle.

Commercial landings data are reported coastwide and by state (CA, OR, WA) by fishery species category; in the case of recreational landings, however, we use the same geographic reporting distinctions but differentiate only between salmon recreational and total recreational landings.

**Indicators**

```{r}
#| echo: false
#| results: 'asis'
erddap_id='cciea_AC_landings'
meta=getMetadata(erddap_id)
num_ind = nrow(meta)

for (i in 1:num_ind){
cat("* **",meta$ERDDAP_query_value[i],"**\n",sep="")
print_meta_about(meta,i)
}
print_meta_remainder(meta,1)
get_github_raw_file(meta$cciea_filename[1],meta$PI_filename[1],meta$no_download[1])
get_erddap_link(erddap_id)
```

**References**

::: {.sectionrefs}
:::
