# Groundfish Stock Abundance
{{< include _setup.qmd >}}

**Description** We present relative Stock Status of groundfish in the CCE as the ratio of the current year spawning biomass (in mt) or output (typically in billions of eggs) to unfished relative to the target reference point (as a percentage of unfished biomass; 0.4 for scorpaenids and other fishes; 0.25 for flatfishes). Fishing Intensity uses the fishing rate to achieve a specific spawner potential ratio (SPR), defined as F/FSPR, where SPR is the maximum sustainable yield (MSY) proxy.

“Overfishing” occurs when catches exceed overfishing limits (OFLs), but not all stocks are managed by OFLs. For summary purposes, our best alternative is to compare fishing rates to proxy rates that are based on a stock’s spawner potential ratio (SPR). Our relative stock status plots present a horizontal line as the fishing intensity rate reference; above the line is above the reference level and indicates overfishing. The vertical lines in the plot represent the biomass target reference points (TRP=1; dashed line) and limit reference points (LRPs; red lines); left of the LRP indicates an overfished status. Symbols indicate taxonomic groups. All points in the plot represent values from the most recent PFMC-adopted full stock assessments. Groundfish stock status data provided by J. Cope, NMFS/NWFSC, derived from NOAA Fisheries stock assessments.

```{r}
#| echo: false
#| results: 'asis'
erddap_id='cciea_GF_ABND'
one_id_byquery(erddap_id,"Species")
#get_erddap_link(erddap_id)
```

**Additional Information**
Data are collected and analyzed independently by J. Cope, who submits unpublished figures and plots to the CCIEA editorial team.

**References**

::: {.sectionrefs}
:::
