# ONI (Oceanic Niño Index)
{{< include _setup.qmd >}}

**Description** The CCLME is driven by atmosphere–ocean energy exchange that occurs on many temporal and spatial scales. El Niño–Southern Oscillation (ENSO) events impact the CCLME by modifying the jet stream and storm tracks, changing the nearshore thermocline, and influencing coastal currents that affect poleward transport and distribution of equatorial and subequatorial waters (and species). The status of the equatorial ENSO is described by the [Oceanic Niño Index](https://www.climate.gov/news-features/understanding-climate/climate-variability-oceanic-nino-index), which tracks the running 3-month average sea surface temperatures in the east-central tropical Pacific between 120°-170°W. An ONI above 0.5°C indicates El Niño conditions, which often lead to lower primary production, weaker upwelling, poleward transport of equatorial waters and species, and more southerly storm tracks in the CCE. An ONI below -0.5°C means La Niña conditions, which create atmospheric pressure conditions that lead to upwelling-favorable winds that drive productivity in the CCE.


```{r}
#| echo: false
#| results: 'asis'

erddap_id='cciea_OC_ONI'
one_id_multimeta(erddap_id)
get_erddap_link(erddap_id)
```

