# Github Actions to read publish CCIEA ESR Tech Docs to gh-pages
# Need to grant read/write permissions for Action to do the commits
# Settings -> Actions -> General -> Workflow permissions
    name: Build Tech Doc
# Use the following to update on push
#    on:
#      push:
#        branches: master
    on:
      workflow_dispatch:
      push:
        branches: [main]
      pull_request:
        branches: [main]

    jobs:
      drive-access:
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository
            uses: actions/checkout@v4

          - name: Authenticate to Google Cloud
            uses: google-github-actions/auth@v2
            with:
              credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
              
          - name: Install system dependencies
            run: |
              sudo apt-get update
              sudo apt-get install -y libcairo2-dev pkg-config
              
          - name: Set up R
            uses: r-lib/actions/setup-r@v2
              
          - name: Install packages
            uses: r-lib/actions/setup-r-dependencies@v2
            with:
              cache: always
              packages: |
                any::tidyverse
                any::httr
                
          - name: Set up Quarto
            uses: quarto-dev/quarto-actions/setup@v2
            env:
              GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

         # This renders the project (good for catching errors in PRs)
          - name: Render Quarto Project
            uses: quarto-dev/quarto-actions/render@v2

          # This only runs if the event is a 'push' (merging to main)
          - name: Publish to GitHub Pages
            if: github.event_name == 'push'
            uses: quarto-dev/quarto-actions/publish@v2
            with:
              target: gh-pages
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
